NUMBER = rand(100)

penny = 1

nickel = 5

dime = 10

quarter = 25
puts number


if NUMBER == 1
  puts "PEEEEEEEEEEEEEEEEEEEEEEEEENNY"

elsif NUMBER == 5
  puts "NIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIICKEEEEEEEEEEEEEEEEEEEEEL"

elsif NUMBER == 10
  puts"DIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIme"

elsif NUMBER == 25
  puts "QUAAAAAAAAAAAAARRRTEEEEEEEEEEEEEEEER"

end
